# Generated by Django 4.2.1 on 2023-05-27 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('answer_id', models.IntegerField()),
                ('choice_1_content', models.CharField(max_length=50)),
                ('choice_2_content', models.CharField(max_length=50)),
                ('choice_3_content', models.CharField(max_length=50)),
                ('choice_4_content', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_choice_id', models.IntegerField()),
                ('correctness', models.BooleanField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzapalooza_app.quiz')),
            ],
        ),
    ]
